### ISSUE TITLE
I met this error when run train.py

### ISSUE THREAD

**Issue by bemoregt** [nmhkahn/pytorch-exercise#2]
Hi, @nmhkahn

I met this error when run train.py

oem@sgi:~/pytorch-exercise/codes/show_and_tell$ python3 train.py 
Traceback (most recent call last):
  File "train.py", line 3, in <module>
    from solver import Solver
  File "/home/oem/pytorch-exercise/codes/show_and_tell/solver.py", line 5, in <module>
    from dataset import get_caption_dataset
  File "/home/oem/pytorch-exercise/codes/show_and_tell/dataset.py", line 9, in <module>
    class CaptionDataset(torch.utils.data.Dataset):
  File "/home/oem/pytorch-exercise/codes/show_and_tell/dataset.py", line 14, in CaptionDataset
    batch_first=True)
  File "/usr/local/lib/python3.6/dist-packages/torchtext/data/field.py", line 152, in __init__
    self.tokenize = get_tokenizer(tokenize)
  File "/usr/local/lib/python3.6/dist-packages/torchtext/data/utils.py", line 12, in get_tokenizer
    spacy_en = spacy.load('en')
  File "/usr/local/lib/python3.6/dist-packages/spacy/__init__.py", line 27, in load
    return util.load_model(name, **overrides)
  File "/usr/local/lib/python3.6/dist-packages/spacy/util.py", line 136, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

What's wrong to me?

My Data Structure -
show_and_tell
- data
-- images
--- 001.Black_ ~
--- 002.Laysan_ ~
--- ....
-- test.csv
-- train.csv
-- download.sh
-- .gitignore

Thanks in advance.
Best Regards.

**Comment by nmhkahn** [comment]
Hi.
Did you execute below command?

python -m spacy download en

If not, maybe it will help.

**Comment by bemoregt** [comment]
@nmhkahn 

OK, I fixed it.
